package com.pfe.adminagent.conversation.web;

import com.pfe.adminagent.conversation.ConversationService;
import com.pfe.adminagent.conversation.dto.ConversationDetailDto;
import com.pfe.adminagent.conversation.dto.ConversationDto;
import com.pfe.adminagent.conversation.dto.CreateConversationRequest;
import com.pfe.adminagent.conversation.dto.MessageDto;
import com.pfe.adminagent.conversation.dto.PostMessageRequest;
import com.pfe.adminagent.security.UserPrincipal;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/conversations")
@Tag(name = "Conversations", description = "AI chat threads (employee ↔ agent)")
@SecurityRequirement(name = "bearerAuth")
public class ConversationController {

    private final ConversationService conversationService;

    public ConversationController(ConversationService conversationService) {
        this.conversationService = conversationService;
    }

    @PostMapping
    @Operation(summary = "Start a new conversation")
    public ResponseEntity<ConversationDto> create(@Valid @RequestBody(required = false) CreateConversationRequest body,
                                                  @AuthenticationPrincipal UserPrincipal principal) {
        String title = body != null ? body.title() : null;
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(conversationService.create(principal.getId(), title));
    }

    @GetMapping
    @Operation(summary = "List the current user's conversations")
    public List<ConversationDto> list(@AuthenticationPrincipal UserPrincipal principal) {
        return conversationService.listForUser(principal.getId());
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get a conversation with its messages")
    public ConversationDetailDto get(@PathVariable UUID id, @AuthenticationPrincipal UserPrincipal principal) {
        return conversationService.getDetail(id, principal.getId());
    }

    @PostMapping("/{id}/messages")
    @Operation(summary = "Post a user message (AI reply is generated by the orchestrator)")
    public ResponseEntity<MessageDto> post(@PathVariable UUID id,
                                           @Valid @RequestBody PostMessageRequest body,
                                           @AuthenticationPrincipal UserPrincipal principal) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(conversationService.postUserMessage(id, principal.getId(), body.content()));
    }
}
